### ISSUE TITLE
Restrict every outgoing traffic except external services

### ISSUE THREAD

**Issue by SilentHunter124** [rancher/network-policy-manager#6]
Dear contributor team,

I would like to trigger a discussion on the following nice feature:

* In "block" mode every outgoing traffic should be blocked
* Watcher scans the stack for statically defined "external services"
* Those External Service IPs are allowed to be reached, nothing else

What do you think about this idea?

**Comment by deniseschannon** [comment]
Can you create this in the rancher/rancher repo? I will be closing the ability to open issues in this repo.
